### ISSUE TITLE
Sep 28 Fixes

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/atsign.dev-3.0#164]
## Tasks Discussed on Sep28 meeting

Feel free to add tasks of your own (in case I missed any)

- [ ] Flutter toc false @JeremyTubongbanua 
- [ ] Get started root _index toc false @JeremyTubongbanua 
- [ ] Noble to review [IoT content](https://docs.atsign.com/start/iot/) @thenobleone14 
- [ ] Root server last image to go to Secondary server page @XavierChanth 
- [ ] Overview in Java codelab @JeremyTubongbanua
