### ISSUE TITLE
devsite 3 | Reference section

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/atsign.dev-3.0#33]
lead: @XavierChanth 

Code:

- [ ] Taxonomy layouts
- [ ] Enable taxonomies in hugo config
- [ ] Taxonomy archetypes
- [ ] Filtering & Categories

Content:

- [x] PKAM & CRAM @JeremyTubongbanua
    #48  
- [x] Encryption @Jesseadriano10 #46 
- [x] Privacy @Jesseadriano10
- [x] Public & Private Key @Jesseadriano10 #46 
- [x] Namespace @JeremyTubongbanua  #65 
- [x] Polymorphism @L1AMcB #60 
- [x] @sign @L1AMcB #59 
- [x] Pricing / Costs @L1AMcB #52 
- [x] Synchronization @Jesseadriano10 #62 
- [x] Self-Encryption Key @JeremyTubongbanua #71 
- [x] Notification @JeremyTubongbanua #64

**Comment by Jesseadriano10** [comment]
Hey can we add Jeremy to this issue! https://github.com/JeremyTubongbanua

**Comment by JeremyTubongbanua** [comment]
The key to @ platform keys
https://docs.google.com/document/d/1JAXNrGr6J30m1xTWD4t7z2eQRo6O7icEOprJh1KKNas/edit

@ protocol
https://docs.google.com/document/d/14PZ-FHV9djBJL1RR8G8aYd6qxiWErBJEvRW9hD0pfNQ/edit

**Comment by JeremyTubongbanua** [comment]
Still need to

- [ ] Be consistent with each definition (through archetype) #70 
- [ ] Add Reference to contribute (so readers know rules for contributing) #70 
- [ ] Proof read every definition
- [ ] Branding changes

**Comment by Jesseadriano10** [comment]
> Still need to
> 
> * [ ]  Be consistent with each definition (through archetype) [Reference tutorials #70](https://github.com/atsign-foundation/atsign.dev-3.0/pull/70)
> * [ ]  Add Reference to contribute (so readers know rules for contributing) [Reference tutorials #70](https://github.com/atsign-foundation/atsign.dev-3.0/pull/70)
> * [ ]  Proof read every definition
> * [ ] Apply branding changings (i.e @platform to atPlatform and so on...)

We will also need to apply the branding changes to this site

**Comment by xavierchanth** [comment]
Closing this for the time being as it is not a priority in the foreseeable future.
